# Generated by Django 5.1.4 on 2024-12-29 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4', 'jpeg', 'gif', 'png'])])),
                ('file_name', models.CharField(max_length=150)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Image', 'Image')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
